### ISSUE TITLE
Stuck at "restoring game data"

### ISSUE THREAD

**Issue by jackieokay** [toffer/minecloud-ami#12]
I'm trying to start a Minecloud server for the first time. The Minecloud AMI is up and running (I can see it in my AWS console) and the instance's public IP corresponds to the server IP listed in the Django app. However, the app is stuck at "Now, it's restoring saved game data. Almost ready..." and I can't join the server in Minecraft. However, I can SSH in. And yess, the minecraft security group in EC2 allows all traffic on port 22 and port 25565. The associated S3 bucket is empty, so I can only assume that the server isn't initializing the game world. Is this a problem with how I configured the server, or a bug? How should I go about initializing game data on the AMI instance ?

**Comment by toffer** [comment]
When you ssh to the Minecloud instance, is the Minecraft server running? Grepping for the msm (minecraft server manager) process should return a result that looks something like this:

```
$ ps aux | grep msm
... SCREEN -dmS msm-default java -Xms1024M ... /opt/msm/servers/default/server.jar nogui
```

Also, does the `/opt/msm/servers/default/world` directory exist? That's where the game data lives, so if the server has been initialized with a new world (which should happen during the AMI build process), you should see something like this:

```
 $ ls -1 /opt/msm/servers/default/
active
banned-ips.txt
banned-players.txt
logs
ops.txt
server.jar
server.log
server.log.offset
server.properties
white-list.txt
world
worldstorage
```

**Comment by verveguy** [comment]
The same symptoms have reappeared based on changes in Oracle's upstream Java downloads. The OAB wrapper appears to be tripping up on x64 arch. See this issue for potential OAB patch https://github.com/flexiondotorg/oab-java6/pull/125

The build_ami.py log will show something like this:

out: notice: /Stage[second]/Oracle_java/Exec[git_clone_oab]/returns: executed successfully
**out: err: /Stage[second]/Oracle_java/Exec[build_java]/returns: change from notrun to 0 failed: /home/oab/oab-java/oab-java.sh -7s returned 1 instead of one of [0] at /home/ubuntu/puppet-minecraft/modules/oracle_java/manifests/init.pp:22**
out: notice: /Stage[second]/Oracle_java/Package[oracle-java7-jre]: Dependency Exec[build_java] has failures: true
out: warning: /Stage[second]/Oracle_java/Package[oracle-java7-jre]: Skipping because of failed dependencies

And checking the underlying log on the EC2 instance itself:

tail -10 /home/ubuntu/oab-java.sh.log

cp -a x64/jre debian/oracle-java7-bin/usr/lib/jvm/java-7-oracle-1.7.0.51
**cp: cannot stat `x64/jre': No such file or directory**
make: **\* [binary-oracle-java7-bin] Error 1
dpkg-buildpackage: error: debian/rules binary gave error exit status 2
^H^H3880's retcode: 2

**Comment by verveguy** [comment]
OK. I've made a patch to use an alternative fork of OAB for the moment. Resolved the problem: I was able to build a new AMI that works again. I'll send a pull request.
